/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RunSession = IDL.Record({
  'id' : IDL.Text,
  'durationSeconds' : IDL.Float64,
  'endTimestamp' : IDL.Int,
  'startTimestamp' : IDL.Int,
  'caloriesBurned' : IDL.Float64,
  'distanceMeters' : IDL.Float64,
  'route' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
});

export const idlService = IDL.Service({
  'getAllRunSessions' : IDL.Func([], [IDL.Vec(RunSession)], ['query']),
  'getAllRunSessionsByEndTime' : IDL.Func([], [IDL.Vec(RunSession)], ['query']),
  'getAllRunSessionsByStartTime' : IDL.Func(
      [],
      [IDL.Vec(RunSession)],
      ['query'],
    ),
  'getRunSession' : IDL.Func([IDL.Text], [IDL.Opt(RunSession)], ['query']),
  'saveRunSession' : IDL.Func([RunSession], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RunSession = IDL.Record({
    'id' : IDL.Text,
    'durationSeconds' : IDL.Float64,
    'endTimestamp' : IDL.Int,
    'startTimestamp' : IDL.Int,
    'caloriesBurned' : IDL.Float64,
    'distanceMeters' : IDL.Float64,
    'route' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
  });
  
  return IDL.Service({
    'getAllRunSessions' : IDL.Func([], [IDL.Vec(RunSession)], ['query']),
    'getAllRunSessionsByEndTime' : IDL.Func(
        [],
        [IDL.Vec(RunSession)],
        ['query'],
      ),
    'getAllRunSessionsByStartTime' : IDL.Func(
        [],
        [IDL.Vec(RunSession)],
        ['query'],
      ),
    'getRunSession' : IDL.Func([IDL.Text], [IDL.Opt(RunSession)], ['query']),
    'saveRunSession' : IDL.Func([RunSession], [], []),
  });
};

export const init = ({ IDL }) => { return []; };